// Manni's World 3.35 — multilingual in-app help guide (SL / DE / EN).
(function(){
  const copy={
    sl:{
      button:'Navodila za uporabo', kicker:'MANNI’S WORLD · NAVODILA', title:'PAMETNEJŠE TANKANJE NA POTI',
      intro:'Manni’s World ti pomaga, da med potjo veš, kdaj in kje se ti najbolj splača tankati. Upošteva tvojo pot, doseg, porabo in cene goriva ter poišče smiselne možnosti ob poti. Navigacija te vodi do cilja, Manni pa ti pomaga pri gorivu, stroških in pravem trenutku za postanek. Tako potuješ bolj mirno, pregledno in praviloma tudi ceneje.',
      gains:'Kaj s tem pridobiš?', chips:['cene goriva ob poti','pameten trenutek za tankanje','pred / po meji','avtocesta / izven avtoceste','10 l varnostne rezerve','stroški poti','zgodovina tankanj'],
      quick:['Nastavi vozilo','Nastavi pot','Preveri priporočilo','Med vožnjo osvežuj','Po tankanju vnesi podatke'],
      s1:'Najprej nastavi vozilo', s1p:'V razdelku Manni & tankanja vnesi velikost rezervoarja, povprečno porabo, trenutno količino goriva in stanje kilometrov. Te podatke Manni uporablja za izračun dosega.', normal:'Normalna rezerva', extreme:'Skrajna spodnja meja', why8:'Manni lahko v posebnem primeru poseže največ približno 20 % v 10-litrsko rezervo, če je naslednja preverjena črpalka bistveno bolj smiselna. Pod približno 8 l ne sme priporočati nadaljevanja.',
      s2:'Nastavi pot – vendar Manni ni navigacija', s2p:'V razdelku Pot nastavi cilj in po potrebi ključne točke Pot preko. Te točke niso nujno postanki; z njimi Manniju nakažeš koridor, po katerem želiš potovati.', choose:'Ko začneš tipkati mesto, vedno izberi pravi kraj iz ponujenih predlogov. Tako Manni shrani točne koordinate in ne ugiba samo po imenu kraja.', example:'Primer: Moja lokacija → Graz → Dunaj → Ostrava → Varšava → Kaunas → Riga → Tallinn', diff:'Pot, ki jo izračuna Manni, se lahko razlikuje od Sygica, Google Maps ali druge navigacije. To je normalno. Sygic lahko upošteva promet, zapore, dimenzije vozila in te med vožnjo preusmeri. Manni uporablja svojo pot predvsem za izračun goriva, črpalk in stroškov.',
      s3:'Če navigacija spremeni pot: OSVEŽI', s3p:'Če te Sygic zaradi zastoja, zapore ali omejitve preusmeri drugam, ni treba na novo sestavljati cele poti v Manniju.', flow:['začetek obvoza','OSVEŽI','voziš','OSVEŽI','vrnitev proti trasi'], refreshDoes:'Ob vsakem Osveži Manni:', refreshSteps:['pridobi trenutno GPS lokacijo','oceni cestne kilometre od zadnje kontrolne točke','iz porabe zmanjša ocenjeno količino goriva','preračuna varen doseg in preostalo pot','ponovno preveri cene in priporočeno tankanje'], detour:'Daljši obvoz? Osveži tudi vmes, npr. po 15–30 minutah. Več krajših GPS segmentov praviloma da boljšo oceno kot samo ena točka na začetku in ena na koncu.', exactOdo:'Za natančno statistiko porabe je še vedno najpomembnejše stanje kilometrov, ki ga vneseš ob tankanju.',
      s4:'Pametno tankanje', s4p:'Manni ne išče samo najcenejšega litra. Najprej preveri, ali je črpalka smiselna glede na tvojo pot, doseg, varnostno rezervo in dejanski prihranek.', rec:'PRIPOROČENO', recd:'najbolj smiselna izbira glede na ceno, doseg, odmik od poti in nadaljevanje poti.', prev:'PREJŠNJA MOŽNOST', prevd:'če želiš tankati nekoliko prej in je postanek še vedno smiseln.', later:'KASNEJŠA / SKRAJNA MOŽNOST', laterd:'če lahko varno nadaljuješ dlje; poseg pod normalnih 10 l je jasno označen.', border:'Tankanje pred ali po meji', borderp:'Ko se približuješ naslednji državi na svoji dejanski poti, Manni primerja preverjene cene pred in po meji. Če je naslednja država občutno cenejša in imaš dovolj dosega, lahko predlaga, da počakaš. Če je trenutna država cenejša, lahko predlaga tankanje še pred mejo.', highway:'Avtocesta ali izven avtoceste?', highwayp:'Če je preverjena črpalka izven avtoceste občutno cenejša, Manni lahko predlaga izvoz. Upošteva dodatni obvoz, količino goriva in dejanski prihranek — zaradi majhne razlike te ne pošilja z avtoceste.', early:'Zakaj včasih predlaga tankanje prej?', earlyp:'Če je pred tabo res ugodna priložnost in bodo naslednji kilometri občutno dražji, lahko Manni priporoči zgodnejše tankanje. Prihranek računa samo na količino, ki jo boš ob prihodu dejansko lahko natočil.',
      s5:'Zemljevid in črpalke', s5p:'Na zemljevidu lahko premakneš pogled kamorkoli po Evropi. Klik na ceno posamezne črpalke odpre njene podatke.', mapchips:['ime in naslov','cena','lokalna valuta + EUR','razdalja','odpiralni čas','Navigiraj'], showmap:'Pri priporočilu izberi Pokaži na zemljevidu. Manni skoči na črpalko in odpre njen popup; nato lahko izbereš Navigiraj.',
      s6:'Kako Manni preverja podatke', s6p:'Aplikacija ne zaupa slepo vsakemu cenovnemu podatku. Za Smart Fuel preverja obstoj črpalke in smiselnost cene.', checks:['Lokacija – ali na mestu dejansko obstaja bencinski servis.','Cena – ali je v realnem razponu glede na državo in primerljive črpalke v okolici.','Tip ceste – avtocestne primerja z avtocestnimi, izven-avtocestne pa med seboj.'], anomaly:'Če je cena močno sumljiva, se postaja lahko izloči iz Smart Fuel priporočila in tudi z zemljevida. Zunanji podatki se lahko kljub temu spremenijo ali so pri posamezni postaji nepopolni.',
      s7:'Ko tankaš', s7p:'Po tankanju vnesi natočene litre, skupni znesek in stanje kilometrov. Če je bil tank napolnjen do vrha, to označi. Manni nato spremlja skupne litre, stroške, povprečno ceno ter dejansko porabo med polnimi tankanji. Delno tankanje je dovoljeno.',
      s8:'Stroški poti', s8p:'Stroški poti združujejo napoved in dejansko stanje med vožnjo. Prikazujejo predvideno razdaljo in porabo, predviden skupni strošek, do zdaj plačano, približno še do cilja, strošek na 100 km, izmerjeno porabo in oceno Smart Fuel prihranka.', s8note:'Ocena se med potjo spreminja glede na prevožene kilometre, nova tankanja, trenutno gorivo, traso in aktualne cene.',
      s9:'Ture, arhiv in osebne nastavitve', s9p:'Za daljšo pot lahko začneš Turo. Tankanja, kilometri in stroški se zbirajo v aktivni turi; na koncu jo zaključiš in shraniš v Arhiv. V Nastavitvah lahko vsak uporabnik na svojem telefonu izbere jezik, ime vozila/aplikacije in svojo naslovno sliko. Ti podatki so lokalni samo na njegovi napravi.',
      shortest:'Najkrajši način uporabe', finalSteps:['Pred potjo: nastavi vozilo, cilj in ključne točke poti.','Preveri Pametno tankanje in okvirne Stroške poti.','Vozi s Sygicom. Če se pot spremeni, občasno pritisni Osveži.','Pred tankanjem: priporočilo → Pokaži na zemljevidu → Navigiraj.','Po tankanju: vnesi litre, znesek in kilometre.'], remember:'Zapomni si: Sygic odloča, po kateri cesti dejansko voziš. Manni pa se ob osvežitvah prilagaja tvojemu realnemu položaju in pomaga odločiti, kje in kdaj je najbolj smiselno tankati.', disclaimer:'Manni je pomoč pri odločanju, ne garancija. Pred večjim odmikom od glavne poti preveri ime črpalke, odpiralni čas in cilj navigacije.', close:'Zapri navodila'
    },
    de:{
      button:'Anleitung', kicker:'MANNI’S WORLD · ANLEITUNG', title:'CLEVERER TANKEN UNTERWEGS',
      intro:'Manni’s World hilft dir unterwegs zu entscheiden, wann und wo sich Tanken am meisten lohnt. Dabei berücksichtigt Manni deine Route, Reichweite, den Verbrauch und die Kraftstoffpreise und sucht sinnvolle Möglichkeiten entlang der Strecke. Die Navigation führt dich zum Ziel, Manni unterstützt dich bei Kraftstoff, Kosten und dem richtigen Zeitpunkt für einen Tankstopp. So reist du entspannter, übersichtlicher und in der Regel auch günstiger.',
      gains:'Was bringt dir Manni?', chips:['Kraftstoffpreise entlang der Route','sinnvoller Tankzeitpunkt','vor / nach der Grenze','Autobahn / abseits der Autobahn','10 l Sicherheitsreserve','Reisekosten','Tankhistorie'],
      quick:['Fahrzeug einstellen','Route festlegen','Empfehlung prüfen','Unterwegs aktualisieren','Nach dem Tanken Daten eintragen'],
      s1:'Zuerst das Fahrzeug einstellen', s1p:'Unter Fahrzeug & Tankvorgänge trägst du Tankvolumen, Durchschnittsverbrauch, aktuellen Kraftstoffstand und Kilometerstand ein. Daraus berechnet Manni deine Reichweite.', normal:'Normale Reserve', extreme:'Absolute Untergrenze', why8:'In einem besonderen Fall darf Manni höchstens etwa 20 % der 10-Liter-Reserve nutzen, wenn die nächste verifizierte Tankstelle deutlich sinnvoller ist. Unter ungefähr 8 l darf Manni kein Weiterfahren empfehlen.',
      s2:'Route festlegen – Manni ist aber keine Navigation', s2p:'Unter Route gibst du das Ziel und bei Bedarf wichtige Punkte unter Route über ein. Diese Punkte sind keine Pflichtstopps; sie beschreiben den Korridor, den du fahren möchtest.', choose:'Wenn du einen Ort eingibst, wähle ihn immer aus den Vorschlägen aus. So speichert Manni die exakten Koordinaten und muss den Ortsnamen nicht erraten.', example:'Beispiel: Mein Standort → Graz → Wien → Ostrava → Warschau → Kaunas → Riga → Tallinn', diff:'Die von Manni berechnete Route kann von Sygic, Google Maps oder einer anderen Navigation abweichen. Das ist normal. Sygic kann Verkehr, Sperren, Fahrzeugabmessungen und Umleitungen berücksichtigen. Manni nutzt seine Route vor allem zur Berechnung von Kraftstoff, Tankstellen und Kosten.',
      s3:'Wenn die Navigation die Route ändert: AKTUALISIEREN', s3p:'Leitet dich Sygic wegen Stau, Sperre oder Einschränkung anders, musst du die gesamte Route in Manni nicht neu aufbauen.', flow:['Beginn der Umleitung','AKTUALISIEREN','weiterfahren','AKTUALISIEREN','zur Route zurück'], refreshDoes:'Bei jeder Aktualisierung:', refreshSteps:['ermittelt Manni deinen aktuellen GPS-Standort','schätzt die Straßenkilometer seit dem letzten Kontrollpunkt','zieht den geschätzten Kraftstoffverbrauch ab','berechnet sichere Reichweite und Reststrecke neu','prüft Preise und Tankempfehlung erneut'], detour:'Längere Umleitung? Aktualisiere auch unterwegs, z. B. nach 15–30 Minuten. Mehrere kurze GPS-Abschnitte liefern in der Regel eine bessere Schätzung als nur ein Punkt am Anfang und einer am Ende.', exactOdo:'Für die genaue Verbrauchsstatistik bleibt der Kilometerstand, den du beim Tanken eingibst, entscheidend.',
      s4:'Intelligentes Tanken', s4p:'Manni sucht nicht einfach nur den billigsten Liter. Zuerst wird geprüft, ob eine Tankstelle zu Route, Reichweite, Sicherheitsreserve und tatsächlicher Ersparnis passt.', rec:'EMPFOHLEN', recd:'die sinnvollste Wahl nach Preis, Reichweite, Abweichung von der Route und weiterem Reiseverlauf.', prev:'FRÜHERE OPTION', prevd:'wenn du etwas früher tanken möchtest und der Stopp weiterhin sinnvoll ist.', later:'SPÄTERE / LETZTE OPTION', laterd:'wenn du sicher weiterfahren kannst; ein Unterschreiten der normalen 10 l wird deutlich markiert.', border:'Vor oder nach der Grenze tanken', borderp:'Wenn du dich dem nächsten Land auf deiner tatsächlichen Route näherst, vergleicht Manni verifizierte Preise vor und nach der Grenze. Ist das nächste Land deutlich günstiger und reicht der Kraftstoff, kann Manni zum Warten raten. Ist das aktuelle Land günstiger, kann Tanken vor der Grenze sinnvoller sein.', highway:'Autobahn oder abseits der Autobahn?', highwayp:'Ist eine verifizierte Tankstelle abseits der Autobahn deutlich günstiger, kann Manni eine Ausfahrt empfehlen. Dabei werden Umweg, Kraftstoffstand und reale Ersparnis berücksichtigt — für einen kleinen Preisunterschied wirst du nicht von der Autobahn geschickt.', early:'Warum empfiehlt Manni manchmal frühes Tanken?', earlyp:'Liegt eine wirklich günstige Gelegenheit vor dir und wird Kraftstoff danach deutlich teurer, kann Manni früheres Tanken empfehlen. Die Ersparnis wird nur mit der Menge berechnet, die bei Ankunft tatsächlich in den Tank passt.',
      s5:'Karte und Tankstellen', s5p:'Du kannst die Karte überall in Europa verschieben. Ein Tipp auf den Preis einer Tankstelle öffnet ihre Details.', mapchips:['Name und Adresse','Preis','lokale Währung + EUR','Entfernung','Öffnungszeiten','Navigieren'], showmap:'Wähle in einer Empfehlung Auf Karte zeigen. Manni springt zur Tankstelle und öffnet das Infofenster; anschließend kannst du Navigieren wählen.',
      s6:'Wie Manni Daten prüft', s6p:'Die App vertraut nicht blind jedem Preis. Für Smart Fuel prüft sie, ob die Tankstelle existiert und ob der Preis plausibel ist.', checks:['Standort – gibt es dort tatsächlich eine Tankstelle?','Preis – liegt er in einem realistischen Bereich für Land und vergleichbare Stationen in der Umgebung?','Straßentyp – Autobahntankstellen werden mit Autobahntankstellen verglichen, andere untereinander.'], anomaly:'Ist ein Preis stark verdächtig, kann die Station aus Smart Fuel und auch von der Karte entfernt werden. Externe Daten können sich trotzdem ändern oder bei einzelnen Stationen unvollständig sein.',
      s7:'Nach dem Tanken', s7p:'Trage getankte Liter, Gesamtbetrag und Kilometerstand ein. War der Tank danach voll, markiere das. Manni verfolgt dann Gesamtmenge, Kosten, Durchschnittspreis und den gemessenen Verbrauch zwischen Volltankungen. Teilbetankungen sind möglich.',
      s8:'Reisekosten', s8p:'Reisekosten verbinden Prognose und tatsächlichen Verlauf. Angezeigt werden voraussichtliche Strecke und Kraftstoffmenge, geschätzte Gesamtkosten, bisher bezahlt, voraussichtlich noch bis zum Ziel, Kosten pro 100 km, gemessener Verbrauch und geschätzte Smart-Fuel-Ersparnis.', s8note:'Die Schätzung verändert sich unterwegs mit gefahrenen Kilometern, neuen Tankvorgängen, aktuellem Kraftstoffstand, Route und Preisen.',
      s9:'Touren, Archiv und persönliche Einstellungen', s9p:'Für längere Reisen kannst du eine Tour starten. Tankvorgänge, Kilometer und Kosten werden in der aktiven Tour gesammelt; am Ende wird sie abgeschlossen und archiviert. Unter Einstellungen kann jeder Nutzer auf seinem Gerät Sprache, App-/Fahrzeugname und eigenes Startbild wählen. Diese Daten bleiben lokal auf diesem Gerät.',
      shortest:'So benutzt du Manni am einfachsten', finalSteps:['Vor der Fahrt: Fahrzeug, Ziel und wichtige Routenpunkte einstellen.','Intelligentes Tanken und ungefähre Reisekosten prüfen.','Mit Sygic fahren. Ändert sich die Route, gelegentlich Aktualisieren drücken.','Vor dem Tanken: Empfehlung → Auf Karte zeigen → Navigieren.','Nach dem Tanken: Liter, Betrag und Kilometerstand eintragen.'], remember:'Merke: Sygic entscheidet, welche Straße du tatsächlich fährst. Manni passt sich bei Aktualisierungen deinem realen Standort an und hilft zu entscheiden, wo und wann Tanken am sinnvollsten ist.', disclaimer:'Manni ist eine Entscheidungshilfe, keine Garantie. Vor einem größeren Umweg immer Tankstellenname, Öffnungszeiten und Navigationsziel prüfen.', close:'Anleitung schließen'
    },
    en:{
      button:'User guide', kicker:'MANNI’S WORLD · USER GUIDE', title:'SMARTER REFUELLING ON THE ROAD',
      intro:'Manni’s World helps you decide when and where it makes the most sense to refuel while travelling. It considers your route, range, fuel consumption and fuel prices to find sensible options along the way. Your navigation app gets you to the destination; Manni helps with fuel, costs and the right time to stop. This makes travelling calmer, clearer and usually cheaper.',
      gains:'What do you gain?', chips:['fuel prices along the route','a sensible time to refuel','before / after a border','motorway / off motorway','10 l safety reserve','trip costs','refuelling history'],
      quick:['Set up vehicle','Set route','Check recommendation','Refresh while driving','Enter data after refuelling'],
      s1:'First set up your vehicle', s1p:'In Vehicle & refuelling enter tank capacity, average consumption, current fuel and odometer. Manni uses these values to calculate your range.', normal:'Normal reserve', extreme:'Absolute lower limit', why8:'In a special case Manni may use at most about 20% of the 10-litre reserve if the next verified station is significantly more sensible. It must not recommend continuing below roughly 8 l.',
      s2:'Set the route – but Manni is not navigation', s2p:'In Route enter your destination and, if needed, important Route via points. They are not mandatory stops; they simply tell Manni which corridor you intend to travel through.', choose:'When you type a place, always select the correct location from the suggestions. This stores exact coordinates instead of making Manni guess from a place name.', example:'Example: My location → Graz → Vienna → Ostrava → Warsaw → Kaunas → Riga → Tallinn', diff:'The route calculated by Manni may differ from Sygic, Google Maps or another navigation app. This is normal. Sygic may account for traffic, closures, vehicle dimensions and rerouting. Manni mainly uses its route to calculate fuel, stations and costs.',
      s3:'If navigation changes the route: REFRESH', s3p:'If Sygic reroutes you because of congestion, a closure or a restriction, you do not need to rebuild the whole route in Manni.', flow:['detour starts','REFRESH','keep driving','REFRESH','back towards route'], refreshDoes:'Each time you press Refresh, Manni:', refreshSteps:['gets your current GPS location','estimates road distance since the last checkpoint','reduces estimated fuel using your consumption','recalculates safe range and remaining route','checks prices and the refuelling recommendation again'], detour:'Longer detour? Refresh during it as well, for example after 15–30 minutes. Several shorter GPS segments will usually give a better estimate than only one point at the start and one at the end.', exactOdo:'For accurate consumption statistics, the odometer value you enter when refuelling remains the key reference.',
      s4:'Smart refuelling', s4p:'Manni does not simply search for the cheapest litre. It first checks whether a station makes sense for your route, range, safety reserve and real saving.', rec:'RECOMMENDED', recd:'the most sensible choice based on price, range, route deviation and what comes next.', prev:'EARLIER OPTION', prevd:'if you prefer to refuel a little sooner and the stop still makes sense.', later:'LATER / LAST-RESORT OPTION', laterd:'if it is still safe to continue; going below the normal 10 l reserve is clearly marked.', border:'Refuel before or after the border', borderp:'As you approach the next country on your actual route, Manni compares verified prices before and after the border. If the next country is clearly cheaper and your range is sufficient, it may recommend waiting. If the current country is cheaper, it may recommend refuelling before the border.', highway:'Motorway or off motorway?', highwayp:'If a verified off-motorway station is substantially cheaper, Manni may suggest leaving the motorway. It considers the extra distance, remaining fuel and real saving — it will not send you off the motorway for a trivial difference.', early:'Why can Manni recommend refuelling early?', earlyp:'If a genuinely good opportunity is ahead and the next stretch is significantly more expensive, Manni may recommend refuelling earlier. Savings are calculated only on the amount you can actually fit into the tank on arrival.',
      s5:'Map and fuel stations', s5p:'Move the map anywhere in Europe. Tap a station price marker to open its details.', mapchips:['name and address','price','local currency + EUR','distance','opening hours','Navigate'], showmap:'From a recommendation choose Show on map. Manni jumps to that station and opens its popup; then choose Navigate.',
      s6:'How Manni checks the data', s6p:'The app does not blindly trust every price. Smart Fuel checks that the station exists and that the price is plausible.', checks:['Location – is there really a fuel station at that point?','Price – is it within a realistic range for the country and comparable nearby stations?','Road type – motorway stations are compared with motorway stations, and off-motorway stations with similar stations.'], anomaly:'If a price is strongly suspicious, the station may be excluded from Smart Fuel and from the map. External data can still change or be incomplete for an individual station.',
      s7:'When you refuel', s7p:'After refuelling, enter litres added, total amount and odometer. If the tank is full afterwards, mark it as full. Manni then tracks total litres, costs, average price and measured consumption between full-tank events. Partial refuelling is allowed.',
      s8:'Trip costs', s8p:'Trip costs combine the forecast with what actually happens while travelling. They show predicted distance and fuel, estimated total cost, paid so far, approximate cost still to destination, cost per 100 km, measured consumption and estimated Smart Fuel saving.', s8note:'The estimate changes while travelling based on distance covered, new refuelling, current fuel, route and current prices.',
      s9:'Trips, archive and personal settings', s9p:'For a longer journey you can start a Trip. Refuelling, kilometres and costs are collected in the active trip; when finished, close it and save it to the Archive. In Settings each user can choose language, app/vehicle name and a personal start image on their own device. These data remain local to that device.',
      shortest:'The simplest way to use Manni', finalSteps:['Before the trip: set the vehicle, destination and important route points.','Check Smart refuelling and approximate Trip costs.','Drive with Sygic. If the route changes, press Refresh from time to time.','Before refuelling: recommendation → Show on map → Navigate.','After refuelling: enter litres, amount and odometer.'], remember:'Remember: Sygic decides which road you actually drive. Manni adapts to your real position when you refresh and helps decide where and when it makes the most sense to refuel.', disclaimer:'Manni is a decision aid, not a guarantee. Before a significant detour, check the station name, opening hours and navigation destination.', close:'Close guide'
    }
  };

  function lang(){return window.ManniI18n?.lang?.()||'sl'}
  function c(){return copy[lang()]||copy.sl}
  function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]))}
  function chips(items){return `<div class="guide-chips">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`}
  function numbered(items){return `<div class="guide-step-list">${items.map((x,i)=>`<div><b>${i+1}</b><span>${esc(x)}</span></div>`).join('')}</div>`}
  function section(n,title,body,accent=''){return `<section class="guide-card ${accent}"><div class="guide-title"><span>${n}</span><h3>${esc(title)}</h3></div>${body}</section>`}
  function recommendation(label,desc){return `<div class="guide-rec"><strong>${esc(label)}</strong><span>${esc(desc)}</span></div>`}
  function render(){
    const x=c();
    return `
      <div class="guide-hero"><div class="guide-kicker">${esc(x.kicker)}</div><h2>${esc(x.title)}</h2><p>${esc(x.intro)}</p></div>
      <section class="guide-card guide-accent"><h3>${esc(x.gains)}</h3>${chips(x.chips)}<div class="guide-quick">${x.quick.map((q,i)=>`<div><b>${i+1}</b><span>${esc(q)}</span></div>`).join('')}</div></section>
      ${section(1,x.s1,`<p>${esc(x.s1p)}</p><div class="guide-metrics"><div><small>${esc(x.normal)}</small><strong>10 l</strong></div><div><small>${esc(x.extreme)}</small><strong>≈ 8 l</strong></div></div><div class="guide-tip">${esc(x.why8)}</div>`)}
      ${section(2,x.s2,`<p>${esc(x.s2p)}</p><p><b>${esc(x.choose)}</b></p><div class="guide-route-demo"><span>📍</span><strong>${esc(x.example)}</strong></div><div class="guide-warn">${esc(x.diff)}</div>`)}
      ${section(3,x.s3,`<p>${esc(x.s3p)}</p><div class="guide-flow">${x.flow.map((f,i)=>`${i?'<i>→</i>':''}<span class="${f.toUpperCase().includes('OSVEŽ')||f.toUpperCase().includes('AKTUAL')||f.toUpperCase().includes('REFRESH')?'refresh':''}">${esc(f)}</span>`).join('')}</div><p><b>${esc(x.refreshDoes)}</b></p>${numbered(x.refreshSteps)}<div class="guide-tip">${esc(x.detour)}</div><p class="guide-muted">${esc(x.exactOdo)}</p>`,'guide-accent')}
      ${section(4,x.s4,`<p>${esc(x.s4p)}</p>${recommendation(x.rec,x.recd)}${recommendation(x.prev,x.prevd)}${recommendation(x.later,x.laterd)}<div class="guide-visual-fuel"><div class="tank"><span style="width:62%"></span></div><small>10 l</small><small class="danger">8 l</small></div><h4>🌍 ${esc(x.border)}</h4><p>${esc(x.borderp)}</p><h4>🛣️ ${esc(x.highway)}</h4><p>${esc(x.highwayp)}</p><h4>⛽ ${esc(x.early)}</h4><p>${esc(x.earlyp)}</p>`)}
      ${section(5,x.s5,`<p>${esc(x.s5p)}</p><div class="guide-map-demo"><div class="road"></div><span class="me">●</span><span class="price p1">1,61 €</span><span class="price p2">1,66 €</span><span class="price p3">1,72 €</span><div class="guide-map-pop"><b>⛽ Fuel station</b><small>1,61 €/l · 3,2 km</small><button>➜ ${esc(x.mapchips[x.mapchips.length-1])}</button></div></div>${chips(x.mapchips)}<div class="guide-tip">${esc(x.showmap)}</div>`)}
      ${section(6,x.s6,`<p>${esc(x.s6p)}</p><div class="guide-checks">${x.checks.map(v=>`<div><b>✓</b><span>${esc(v)}</span></div>`).join('')}</div><div class="guide-warn">${esc(x.anomaly)}</div>`,'guide-accent')}
      ${section(7,x.s7,`<p>${esc(x.s7p)}</p><div class="guide-form-demo"><div><small>L</small><strong>42,6</strong></div><div><small>€</small><strong>68,20</strong></div><div><small>km</small><strong>126.840</strong></div><span>✓ FULL</span></div>`)}
      ${section(8,x.s8,`<p>${esc(x.s8p)}</p><div class="guide-cost-demo"><div><small>≈ km</small><b>1.938</b></div><div><small>≈ l</small><b>194</b></div><div><small>€/100 km</small><b>16,40</b></div></div><div class="guide-tip">${esc(x.s8note)}</div>`)}
      ${section(9,x.s9,`<p>${esc(x.s9p)}</p><div class="guide-profile-demo"><span>🇸🇮 SL</span><span>🇩🇪 DE</span><span>🇬🇧 EN</span><b>📷</b></div>`)}
      <section class="guide-card guide-accent"><h3>${esc(x.shortest)}</h3>${numbered(x.finalSteps)}<div class="guide-remember">${esc(x.remember)}</div></section>
      <div class="guide-disclaimer">⚠️ ${esc(x.disclaimer)}</div>
      <button type="button" id="guideCloseBottom" class="guide-bottom-close">${esc(x.close)}</button>`;
  }
  function ensureDialog(){
    if(document.getElementById('helpGuideDialog'))return;
    const d=document.createElement('dialog');d.id='helpGuideDialog';d.className='guide-dialog';
    d.innerHTML=`<div class="guide-shell"><button type="button" id="guideCloseTop" class="guide-close" aria-label="Close">✕</button><div id="guideContent"></div></div>`;
    document.body.appendChild(d);
    const close=()=>d.close();
    d.querySelector('#guideCloseTop').addEventListener('click',close);
    d.addEventListener('click',e=>{if(e.target===d)close()});
  }
  function openGuide(){ensureDialog();const d=document.getElementById('helpGuideDialog');document.getElementById('guideContent').innerHTML=render();document.getElementById('guideCloseBottom')?.addEventListener('click',()=>d.close());d.showModal();d.querySelector('.guide-shell').scrollTop=0}
  function injectButton(){
    const form=document.querySelector('#settingsDialog form');if(!form||document.getElementById('helpGuideBtn'))return;
    const save=document.getElementById('saveSettingsBtn');
    const b=document.createElement('button');b.type='button';b.id='helpGuideBtn';b.className='guide-open-btn';b.innerHTML=`<span>?</span><strong>${esc(c().button)}</strong><i>›</i>`;
    b.addEventListener('click',openGuide);save?.insertAdjacentElement('beforebegin',b);
  }
  function update(){const b=document.querySelector('#helpGuideBtn strong');if(b)b.textContent=c().button;if(document.getElementById('helpGuideDialog')?.open)document.getElementById('guideContent').innerHTML=render()}
  function init(){ensureDialog();injectButton();window.addEventListener('manni:language-changed',update)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.ManniHelp={open:openGuide};
})();
