// Manni's World 3.12 — confirmed route points + segment validation + GPS checkpoints
(function(){
  const $=id=>document.getElementById(id);
  const ui={panel:$('journeyPanel'),status:$('journeyStatus'),next:$('journeyNext'),nextKm:$('journeyNextKm'),remaining:$('journeyRemaining'),fuel:$('journeyFuel'),safe:$('journeySafeRange'),note:$('journeyNote'),segment:$('journeySegmentKm'),tracked:$('journeyTrackedKm')};
  if(!ui.panel||!window.ManniStorage)return;
  const OSRM='https://router.project-osrm.org/route/v1/driving/';let busy=false;
  function fmtKm(v){return Number.isFinite(v)?`${v<10?v.toFixed(1).replace('.',','):Math.round(v).toLocaleString((window.ManniI18n?.locale?.()||'sl-SI'))} km`:'—'}
  function fmtL(v){return Number.isFinite(v)?`${v.toFixed(1).replace('.',',')} l`:'—'}
  function hav(a,b){const R=6371,p=Math.PI/180,da=(b.lat-a.lat)*p,dl=(b.lon-a.lon)*p,x=Math.sin(da/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
  function currentPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('GPS ni na voljo.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy}),()=>reject(new Error('Lokacije ni bilo mogoče pridobiti. Dovoli GPS.')),{enableHighAccuracy:true,timeout:12000,maximumAge:15000})})}
  async function roadRoute(points){if(points.length<2)return null;const coords=points.map(p=>`${p.lon},${p.lat}`).join(';'),u=new URL(OSRM+coords);u.searchParams.set('overview','full');u.searchParams.set('geometries','geojson');u.searchParams.set('steps','false');const r=await fetch(u,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error('Routing '+r.status);const j=await r.json();if(j.code!=='Ok'||!j.routes?.length)throw new Error('Cestne poti ni bilo mogoče izračunati.');return {km:j.routes[0].distance/1000,min:j.routes[0].duration/60,legs:j.routes[0].legs||[],geometry:j.routes[0].geometry||null}}
  function liveFuel(data){const base=Number(data.vehicle?.currentFuelLitres),avg=Number(data.vehicle?.averageConsumption),tracked=Number(data.journey?.trackedKm||0);if(!Number.isFinite(base))return null;if(!Number.isFinite(avg)||avg<=0)return base;return Math.max(0,base-tracked*avg/100)}
  function safeRange(data){const f=liveFuel(data),avg=Number(data.vehicle?.averageConsumption);if(!Number.isFinite(f)||!Number.isFinite(avg)||avg<=0)return null;return Math.max(0,f-10)/avg*100}
  function routePoints(r){const via=Array.isArray(r.viaPoints)?r.viaPoints:[];const dest=r.destinationPoint;return dest?[...via,dest].map((p,i)=>({name:p.label||p.name,label:p.label||p.name,country:p.country||'',lat:Number(p.lat),lon:Number(p.lon),kind:i===via.length?'destination':'via'})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)):[]}
  function routeComplete(r){const startOk=r.startMode!=='manual'||!!r.startPoint;return startOk&&!!r.destinationPoint && (r.via||[]).length===(r.viaPoints||[]).length}
  function passedWaypoint(prev,wp,pos){if(hav(pos,wp)<=25)return true;if(!prev)return false;const x=wp.lon-prev.lon,y=wp.lat-prev.lat,den=x*x+y*y;if(den<1e-9)return false;const t=((pos.lon-prev.lon)*x+(pos.lat-prev.lat)*y)/den,corridor=hav(pos,wp);return t>1.03&&corridor<120}
  function ensureValidationEl(){let el=$('routeValidation');if(!el){el=document.createElement('div');el.id='routeValidation';el.className='route-validation';ui.note.insertAdjacentElement('afterend',el)}return el}
  function segmentValidation(points,route){const legs=route?.legs||[],segments=[];for(let i=0;i<legs.length;i++){const a=points[i],b=points[i+1],km=Number(legs[i]?.distance)/1000,direct=hav(a,b);const ratio=direct>1?km/direct:1,duplicate=direct<0.25;const valid=Number.isFinite(km)&&km>0.2&&!duplicate&&km<1800&&ratio<3.8;segments.push({from:a.name||'Trenutna lokacija',to:b.name,km,directKm:direct,duplicate,valid})}return segments}
  function renderValidation(j){const el=ensureValidationEl(),segs=j.routeSegments||[];if(!segs.length){el.innerHTML='';return}el.innerHTML=`<div class="route-validation-head"><strong>Preverba poti po odsekih</strong><span class="${j.routeValid?'ok':'bad'}">${j.routeValid?'✓ pot je smiselna':'⚠ preveri pot'}</span></div>${segs.map(s=>`<div class="route-segment ${s.valid?'':'bad'}"><span>${s.from} → ${s.to}</span><strong>${fmtKm(s.km)}</strong></div>`).join('')}${j.validationMessage?`<p>${j.validationMessage}</p>`:''}`}
  function renderFromStored(){const d=window.ManniStorage.get(),j=d.journey||{},r=d.route||{},sr=safeRange(d),fuel=liveFuel(d);ui.panel.hidden=!r.destination;if(!r.destination)return;ui.fuel.textContent=fmtL(fuel);ui.safe.textContent=fmtKm(sr);if(ui.segment)ui.segment.textContent=fmtKm(j.lastSegmentKm);if(ui.tracked)ui.tracked.textContent=fmtKm(Number(j.trackedKm||0));const pts=j.resolvedPoints||[],idx=Math.min(j.nextIndex||0,Math.max(0,pts.length-1));ui.next.textContent=pts[idx]?.name||'—';ui.nextKm.textContent=fmtKm(j.lastNextKm);ui.remaining.textContent=fmtKm(j.lastRouteKm);if(!routeComplete(r))ui.status.textContent='⚠ Pot vsebuje stare/nepotrjene točke. Odpri Pot in jih izberi iz predlogov.';else if(j.updatedAt){const t=new Date(j.updatedAt).toLocaleTimeString((window.ManniI18n?.locale?.()||'sl-SI'),{hour:'2-digit',minute:'2-digit'});ui.status.textContent=`Nazadnje osveženo ob ${t}`}else ui.status.textContent='Pot še ni preračunana.';if(!Number.isFinite(sr))ui.note.textContent='Za doseg najprej vnesi trenutno gorivo in povprečno porabo v ⛽ Manni & tankanja.';else if(j.routeValid===false)ui.note.textContent='Pametno tankanje je začasno ustavljeno, dokler ne popraviš sumljive točke poti.';else if(Number.isFinite(j.lastNextKm)&&j.lastNextKm>sr)ui.note.textContent='Naslednja točka je izven varnega dosega. Pred njo bo potrebno tankanje.';else if(r.startMode==='manual')ui.note.textContent='Izračun je narejen od ročno izbrane začetne lokacije. Za vožnjo v živo lahko začetek kadarkoli preklopiš na »Moja trenutna lokacija«.';else ui.note.textContent='GPS kontrolne točke ocenjujejo sproti prevožene kilometre. Za natančno statistiko ostane merodajen števec kilometrov ob tankanju.';renderValidation(j)}
  async function refresh(){if(busy)return;busy=true;ui.status.textContent='Osvežujem kilometre in potrjeno pot …';try{let data=window.ManniStorage.get(),r=data.route||{};if(!r.destination)throw new Error('Najprej nastavi cilj v razdelku Pot.');if(!routeComplete(r))throw new Error('Odpri Pot in vsako točko ponovno izberi iz ponujenega seznama.');const pts=routePoints(r);if(!pts.length)throw new Error('Pot nima potrjenih koordinat.');const manual=r.startMode==='manual'&&r.startPoint;let pos,segmentKm=0;
    if(manual){pos={lat:Number(r.startPoint.lat),lon:Number(r.startPoint.lon),name:r.start||r.startPoint.label||'Začetek'};if(!Number.isFinite(pos.lat)||!Number.isFinite(pos.lon))throw new Error('Začetna lokacija nima potrjenih koordinat.');window.ManniStorage.update(d=>{const j=d.journey||(d.journey={});j.lastSegmentKm=0;j.trackedKm=0;j.lastPosition=null;j.lastCheckpointAt=null;j.checkpoints=[];j.estimatedFuelLitres=d.vehicle.currentFuelLitres;return d});}
    else {pos=await currentPosition();const prev=data.journey?.lastPosition;if(prev&&hav(prev,pos)>0.08){try{const seg=await roadRoute([prev,pos]);if(seg&&Number.isFinite(seg.km)&&seg.km<500)segmentKm=seg.km}catch(e){console.warn('Checkpoint routing',e)}}window.ManniStorage.update(d=>{const j=d.journey||(d.journey={}),tracked=Math.max(0,Number(j.trackedKm||0)+(Number.isFinite(segmentKm)?segmentKm:0));j.lastSegmentKm=segmentKm;j.trackedKm=tracked;j.lastPosition={lat:pos.lat,lon:pos.lon};j.lastCheckpointAt=new Date().toISOString();j.checkpoints=[...(j.checkpoints||[]),{lat:pos.lat,lon:pos.lon,timestamp:j.lastCheckpointAt,segmentKm}].slice(-100);const base=Number(d.vehicle?.currentFuelLitres),avg=Number(d.vehicle?.averageConsumption);j.estimatedFuelLitres=Number.isFinite(base)&&Number.isFinite(avg)&&avg>0?Math.max(0,base-tracked*avg/100):(Number.isFinite(base)?base:null);return d});}
    data=window.ManniStorage.get();let idx=manual?0:Math.min(data.journey?.nextIndex||0,pts.length-1),startCoord=manual?{lat:pos.lat,lon:pos.lon}:data.journey?.startCoord||{lat:pos.lat,lon:pos.lon};if(!manual){while(idx<pts.length-1){const previous=idx===0?startCoord:pts[idx-1];if(passedWaypoint(previous,pts[idx],pos))idx++;else break}}
    const startName=manual?(r.start||r.startPoint.label||'Začetek'):'Trenutna lokacija';const remaining=[{...pos,name:startName},...pts.slice(idx)],route=await roadRoute(remaining),nextRoute=await roadRoute([pos,pts[idx]]),segments=segmentValidation(remaining,route),valid=segments.every(s=>s.valid);const bad=segments.find(s=>!s.valid);window.ManniStorage.update(d=>{d.journey={...d.journey,startCoord,nextIndex:idx,resolvedPoints:pts,routeValid:valid,routeSegments:segments,validationMessage:bad?(bad.duplicate?`Podvojena točka: ${bad.to} je že prejšnja točka oziroma cilj. Odstrani podvojeni vnos.`:`Odsek ${bad.from} → ${bad.to} je neobičajen glede na izbrane točke. Preveri točko pred nadaljevanjem.`):null,lastRouteKm:valid?(route?.km??null):null,lastNextKm:valid?(nextRoute?.km??null):null,lastDurationMin:valid?(route?.min??null):null,updatedAt:new Date().toISOString()};return d});renderFromStored();if(valid&&route?.geometry?.coordinates)window.dispatchEvent(new CustomEvent('manni:route-geometry',{detail:{coordinates:route.geometry.coordinates}}));window.dispatchEvent(new CustomEvent('manni:route-validated',{detail:{valid}}))}catch(e){console.warn('Journey refresh',e);ui.status.textContent=e.message||'Poti ni bilo mogoče preračunati.';window.ManniStorage.update(d=>{d.journey.routeValid=false;d.journey.validationMessage=e.message||'Poti ni bilo mogoče potrditi.';d.journey.lastRouteKm=null;d.journey.lastNextKm=null;return d});renderFromStored();window.dispatchEvent(new CustomEvent('manni:route-validated',{detail:{valid:false}}))}finally{busy=false}}
  function resetFuelTracking(){window.ManniStorage.update(d=>{d.journey.trackedKm=0;d.journey.lastSegmentKm=0;d.journey.estimatedFuelLitres=d.vehicle.currentFuelLitres;d.journey.checkpoints=[];return d});renderFromStored()}
  window.addEventListener('manni:checkpoint-request',refresh);window.addEventListener('manni:fuel-changed',resetFuelTracking);window.addEventListener('manni:trip-changed',renderFromStored);window.addEventListener('manni:route-changed',()=>{window.ManniStorage.update(d=>{d.journey.nextIndex=0;d.journey.startCoord=null;d.journey.resolvedPoints=[];d.journey.routeValid=null;d.journey.routeSegments=[];d.journey.validationMessage=null;d.journey.updatedAt=null;return d});renderFromStored();setTimeout(refresh,180)});renderFromStored();setTimeout(()=>{if(window.ManniStorage.get().route?.destination)refresh()},1000);console.info('Manni 3.15 route validation ready');
})();
