// Manni's World 3.12 — route autocomplete + confirmed coordinates
(function(){
  const $=id=>document.getElementById(id);
  const ui={btn:$('routeBtn'),dialog:$('routeDialog'),close:$('routeCloseBtn'),destination:$('routeDestination'),viaList:$('routeViaList'),add:$('addViaBtn'),save:$('saveRouteBtn'),clear:$('clearRouteBtn'),summary:$('routeSummary'),badge:$('routeBadge')};
  if(!ui.btn||!ui.dialog||!window.ManniStorage)return;
  const PHOTON='https://photon.komoot.io/api/';
  let draftDestination={text:'',point:null},draftVia=[];
  let timer=null,activeBox=null,requestSeq=0;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  function pointLabel(p){if(!p)return '';return p.label||[p.name,p.city!==p.name?p.city:'',p.state,p.country].filter(Boolean).join(', ')}
  function photonPoint(f){const p=f?.properties||{},c=f?.geometry?.coordinates;if(!Array.isArray(c)||c.length<2)return null;const name=p.name||p.city||p.county||p.state||'Lokacija';const city=p.city||p.locality||'';const state=p.state||'';const country=p.country||'';const parts=[];for(const x of [name,city&&city!==name?city:'',state&&state!==city?state:'',country])if(x&&!parts.includes(x))parts.push(x);return {label:parts.join(', '),name,city,state,country,countryCode:String(p.countrycode||'').toUpperCase(),lat:Number(c[1]),lon:Number(c[0])}}
  function current(){return window.ManniStorage.get().route}
  function closeSuggestions(){if(activeBox){activeBox.remove();activeBox=null}}
  function suggestionBox(input,items,onPick){closeSuggestions();const box=document.createElement('div');box.className='route-suggestions';if(!items.length){box.innerHTML='<div class="route-suggestion-empty">Ni zadetkov. Poskusi z imenom kraja in državo.</div>'}else items.forEach(p=>{const b=document.createElement('button');b.type='button';b.className='route-suggestion';b.innerHTML=`<strong>${esc(p.name)}</strong><span>${esc([p.city!==p.name?p.city:'',p.state,p.country].filter(Boolean).join(', '))}</span>`;b.addEventListener('click',()=>{onPick(p);closeSuggestions()});box.appendChild(b)});const wrap=input.closest('.route-autocomplete-wrap')||input.parentElement;wrap.appendChild(box);activeBox=box}
  async function search(input,onPick){const q=input.value.trim();if(q.length<2){closeSuggestions();return}const seq=++requestSeq;const u=new URL(PHOTON);u.searchParams.set('q',q);u.searchParams.set('limit','7');u.searchParams.set('lang','en');try{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw 0;const j=await r.json();if(seq!==requestSeq)return;const items=(j.features||[]).map(photonPoint).filter(Boolean);suggestionBox(input,items,onPick)}catch{if(seq===requestSeq)suggestionBox(input,[],onPick)}}
  function scheduleSearch(input,onPick){clearTimeout(timer);timer=setTimeout(()=>search(input,onPick),280)}
  function ensureDestWrap(){if(ui.destination.parentElement?.classList.contains('route-autocomplete-wrap'))return;const w=document.createElement('div');w.className='route-autocomplete-wrap';ui.destination.parentNode.insertBefore(w,ui.destination);w.appendChild(ui.destination)}
  function updateBadge(){const r=current();if(r.destination){ui.badge.textContent=r.destination;ui.badge.hidden=false;ui.summary.textContent=`Moja lokacija → ${r.via.length?r.via.join(' → ')+' → ':''}${r.destination}${r.destinationPoint?'':' · ⚠ ponovno izberi kraj'}`}else{ui.badge.hidden=true;ui.summary.textContent='Pot še ni nastavljena.'}}
  function renderVia(){ui.viaList.innerHTML='';if(!draftVia.length){ui.viaList.innerHTML='<div class="route-empty">Vmesne točke niso obvezne. Pri dodani točki začni tipkati in nato izberi pravi kraj iz predlogov.</div>';return}draftVia.forEach((item,i)=>{const row=document.createElement('div');row.className='via-row';row.innerHTML=`<div class="route-autocomplete-wrap via-autocomplete"><input class="via-input ${item.point?'route-confirmed':'route-unconfirmed'}" data-i="${i}" value="${esc(item.text)}" placeholder="npr. Dunaj"><span class="route-confirm-mark">${item.point?'✓':'!'}</span></div><div class="via-actions"><button type="button" data-act="up" data-i="${i}">↑</button><button type="button" data-act="down" data-i="${i}">↓</button><button type="button" data-act="remove" data-i="${i}">✕</button></div>`;ui.viaList.appendChild(row)})}
  function open(){const r=current();draftDestination={text:r.destination||'',point:r.destinationPoint||null};draftVia=(r.via||[]).map((text,i)=>({text,point:(r.viaPoints||[])[i]||null}));ui.destination.value=draftDestination.text;ui.destination.classList.toggle('route-confirmed',!!draftDestination.point);ui.destination.classList.toggle('route-unconfirmed',!draftDestination.point&&!!draftDestination.text);renderVia();ui.dialog.showModal()}
  function validateDraft(){if(!draftDestination.text.trim())return 'Vnesi cilj poti.';if(!draftDestination.point)return 'Cilj izberi iz ponujenega seznama, da Manni shrani pravilne koordinate.';for(let i=0;i<draftVia.length;i++){if(draftVia[i].text.trim()&&!draftVia[i].point)return `Točko »${draftVia[i].text}« izberi iz ponujenega seznama.`}return null}
  function save(){const err=validateDraft();if(err){ui.summary.textContent='⚠ '+err;ui.summary.classList.add('route-summary-warning');return}ui.summary.classList.remove('route-summary-warning');const viaItems=draftVia.filter(x=>x.text.trim()&&x.point);window.ManniStorage.update(data=>{data.route={destination:pointLabel(draftDestination.point),destinationPoint:draftDestination.point,via:viaItems.map(x=>pointLabel(x.point)),viaPoints:viaItems.map(x=>x.point),updatedAt:new Date().toISOString()};return data});updateBadge();window.dispatchEvent(new CustomEvent('manni:route-changed'));ui.dialog.close()}
  function clear(){window.ManniStorage.update(data=>{data.route={destination:'',destinationPoint:null,via:[],viaPoints:[],updatedAt:new Date().toISOString()};return data});draftDestination={text:'',point:null};draftVia=[];ui.destination.value='';renderVia();updateBadge();window.dispatchEvent(new CustomEvent('manni:route-changed'))}
  ensureDestWrap();
  ui.destination.addEventListener('input',()=>{draftDestination.text=ui.destination.value;draftDestination.point=null;ui.destination.classList.remove('route-confirmed');ui.destination.classList.toggle('route-unconfirmed',!!ui.destination.value.trim());scheduleSearch(ui.destination,p=>{draftDestination={text:pointLabel(p),point:p};ui.destination.value=draftDestination.text;ui.destination.classList.add('route-confirmed');ui.destination.classList.remove('route-unconfirmed')})});
  ui.destination.addEventListener('focus',()=>{if(ui.destination.value.trim().length>=2&&!draftDestination.point)scheduleSearch(ui.destination,p=>{draftDestination={text:pointLabel(p),point:p};ui.destination.value=draftDestination.text;ui.destination.classList.add('route-confirmed');ui.destination.classList.remove('route-unconfirmed')})});
  ui.btn.addEventListener('click',open);ui.close.addEventListener('click',()=>{closeSuggestions();ui.dialog.close()});
  ui.add.addEventListener('click',()=>{draftVia.push({text:'',point:null});renderVia();setTimeout(()=>ui.viaList.querySelector('.via-input:last-of-type')?.focus(),0)});
  ui.save.addEventListener('click',save);ui.clear.addEventListener('click',clear);
  ui.viaList.addEventListener('input',e=>{if(!e.target.matches('.via-input'))return;const i=Number(e.target.dataset.i);draftVia[i].text=e.target.value;draftVia[i].point=null;e.target.classList.remove('route-confirmed');e.target.classList.toggle('route-unconfirmed',!!e.target.value.trim());scheduleSearch(e.target,p=>{draftVia[i]={text:pointLabel(p),point:p};e.target.value=draftVia[i].text;e.target.classList.add('route-confirmed');e.target.classList.remove('route-unconfirmed');const mark=e.target.parentElement.querySelector('.route-confirm-mark');if(mark)mark.textContent='✓'})});
  ui.viaList.addEventListener('focusin',e=>{if(!e.target.matches('.via-input'))return;const i=Number(e.target.dataset.i);if(e.target.value.trim().length>=2&&!draftVia[i].point)scheduleSearch(e.target,p=>{draftVia[i]={text:pointLabel(p),point:p};e.target.value=draftVia[i].text;e.target.classList.add('route-confirmed');e.target.classList.remove('route-unconfirmed');const mark=e.target.parentElement.querySelector('.route-confirm-mark');if(mark)mark.textContent='✓'})});
  ui.viaList.addEventListener('click',e=>{const b=e.target.closest('button[data-act]');if(!b)return;closeSuggestions();const i=Number(b.dataset.i),act=b.dataset.act;if(act==='remove')draftVia.splice(i,1);if(act==='up'&&i>0)[draftVia[i-1],draftVia[i]]=[draftVia[i],draftVia[i-1]];if(act==='down'&&i<draftVia.length-1)[draftVia[i+1],draftVia[i]]=[draftVia[i],draftVia[i+1]];renderVia()});
  document.addEventListener('click',e=>{if(activeBox&&!e.target.closest('.route-autocomplete-wrap'))closeSuggestions()});
  window.addEventListener('manni:trip-changed',updateBadge);updateBadge();
  console.info('Manni 3.12 route autocomplete ready');
})();
